services:
  danmurphy-cellar-notifier:
    build: .
    container_name: danmurphy-cellar-notifier

    volumes:
      - ./:/app
      - danmurphy-data:/data

    restart: unless-stopped

    environment:
      - TZ=Australia/Brisbane
      - PYTHONUNBUFFERED=1
      - TELEGRAM_TOKEN=<INSERT_HERE>
      - TELEGRAM_CHAT_ID=<INSERT_HERE>
      - DISCORD_WEBHOOK_URL=<URL>

volumes:
  danmurphy-data:
